apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: guestbook
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: practice2
    app.kubernetes.io/created-by: majid-roudi
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: frontend
    spec:
      containers:
        - name: php-redis
          image: majidroodi/guestbook-frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REDIS_HOST
              value: redis
            -  name: REDIS_PORT
               value: "6379" 
          readinessProbe:
            httpGet:
              path: /index.php
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
            limits:
              cpu: "300m"
              memory: "256Mi"

