---
- hosts: all
  vars_files:
    - secret.yaml
  vars:
    my_password: "{{ vault_my_password }}"
    package_to_be_installed:
      - haproxy
      - curl
      - keepalived
  tasks:
    - name: install required packages
      apt:
        name: "{{ package_to_be_installed }}"