apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: practice
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: jenkins
      app.kubernetes.io/part-of: practice
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jenkins
        app.kubernetes.io/part-of: practice
    spec:
      containers:
        - name: jenkins
          image: docker.io/jenkins/jenkins:latest
          env:
            - name: DOCKER_HOST
              value: tcp://docker:2376
            - name: DOCKER_TLS_VERIFY
              value: "1"
            - name: TZ
              value: Asia/Tehran
            - name: JAVA_OPTS
              value: -Duser.timezone=Asia/Tehran
          ports:
            - containerPort: 50000
            - containerPort: 8080

          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          startupProbe:
            httpGet:
              path: /login
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10

          volumeMounts:
            - name: jenkins-volume
              mountPath: /var/jenkins_home

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1024Mi"

      volumes:
        - name: jenkins-volume
          emptyDir: {}

