apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: default
  labels:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: practice
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jenkins
    app.kubernetes.io/part-of: practice
  ports:
  - name: http
    protocol: TCP
    port: 8080          # Service port inside cluster
    targetPort: 8080    # Container port
    nodePort: 32080     # NodePort (for external access)
  - name: agent
    protocol: TCP
    port: 50000
    targetPort: 50000
    nodePort: 32050
