apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: guestbook
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: practice2
    app.kubernetes.io/created-by: majid-roudi
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
    spec:
      containers:
        - name: redis
          image: redis:6.2
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: "250m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc

