apiVersion: v1
kind: ConfigMap
metadata:
  name: default-config
  namespace: reverse-proxy
data:
  default.conf: |
    upstream backend {
        server echoserver-nodeport.reverse-proxy.svc.cluster.local:8080;
        keepalive 16;
    }

    server {
        listen 80 default_server;
        server_name _;
        return 444;
    }

    server {
        listen 80;
        server_name *.local.net;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl http2;
        server_name *.local.net;

        ssl_certificate     /etc/nginx/ssl/tls.crt;
        ssl_certificate_key /etc/nginx/ssl/tls.key;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass http://backend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $host;
            proxy_set_header X-Forwarded-Port $server_port;
            proxy_connect_timeout 900s;
            proxy_send_timeout 900s;
            proxy_read_timeout 3600s;
            proxy_set_header Connection "";
        }
    }
