apiVersion: v1
kind: Service
metadata:
  name: nginx-reverse-proxy
  namespace: reverse-proxy
  labels:
    app.kubernetes.io/name: nginx-reverse-proxy
    app.kubernetes.io/part-of: practice
    app.kubernetes.io/created-by: majid-roudi
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx-reverse-proxy
    app.kubernetes.io/part-of: practice
    app.kubernetes.io/created-by: majid-roudi
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30083
  - name: https
    port: 443
    targetPort: 443
    nodePort: 30084
