apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-proxy-config
  namespace: reverse-proxy
data:
  nginx.conf: |
    worker_processes auto;
    worker_rlimit_nofile 100000;

    events {
        worker_connections 65536;
    }

    http {
        sendfile on;
        tcp_nopush on;
        tcp_nodelay on;

        client_max_body_size 300M;
        client_body_buffer_size 1M;

        keepalive_timeout 65;
        keepalive_requests 10000;

        include /etc/nginx/mime.types;
        default_type application/octet-stream;

        log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

        access_log /var/log/nginx/access.log main;
        error_log /var/log/nginx/error.log warn;

        include /etc/nginx/conf.d/*.conf;
    }
